### ISSUE TITLE
代码clone下来，已经安装好依赖项了，怎么无法打包啊？

### ISSUE THREAD

**Issue by winkingforme** [Yi-love/webpack4-demo#3]
![image](https://user-images.githubusercontent.com/20579220/45078590-ff98ab80-b122-11e8-937b-9193e77c2a8f.png)
setp_2 分支

**Comment by feelslive** [comment]
setp_2 分支

**Comment by liyongfen** [comment]
我也碰到clone下拉的代码，npm install后，再webpack，也是报错，通过报错信息看出是webpack和webpack-cli版本不符，重新安装了webpack-cli就可以了。你的问题安装了webpack?
